# Use official Python image
FROM python:3.10

# Set working directory
WORKDIR /app

# Copy all files to working directory
COPY . .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Expose the port Flask will run on
EXPOSE 5000

# Run the app
CMD ["gunicorn", "bot:app", "--bind", "0.0.0.0:5000"]
